
manifest:
  remotes:
    - name: teamspatzenhirn
      url-base: https://github.com/teamspatzenhirn
  projects:
    - name: pmw3389_zephyr_driver
      remote: teamspatzenhirn
      revision: 837e0ab2182d8748b46bf188f03c7dde4d4e0328
      path: modules/pmw3389
